name: "cypress-load-balancer/save-on-pull-request"
description: "A simple load balancer for Cypress tests. Saves the load balancing map on pull request merges to the base branch."
author: Zachary J. Hamm
branding:
  icon: "cpu"
  color: "green"

inputs:
  image:
    description: The image to use for running the action
    default: ubuntu-22.04
  node-version:
    description: The node version to use for JS actions

runs:
  using: composite
  steps:
    - name: Get cached load-balancing map for current branch
      id: cache-restore-load-balancing-map
      uses: actions/cache/restore@v4
      with:
        fail-on-cache-miss: true
        path: .cypress_load_balancer/main.json
        key: cypress-load-balancer-map--${{ github.head_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          cypress-load-balancer-map-${{ github.head_ref }}

    - name: Get cached load-balancing map for base branch, if existing
      id: cache-restore-load-balancing-map
      uses: actions/cache/restore@v4
      with:
        fail-on-cache-miss: false
        path: .cypress_load_balancer_temp/base/main.json
        key: cypress-load-balancer-map--${{ github.base_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          cypress-load-balancer-map-${{ github.base_ref }}

    - name: Merge load balancing map files
      run: npx cypress-load-balancer merge -G "./cypress_load_balancer_temp/base/main.json"
      shell: bash

    - name: Save cached load-balancing map
      id: cache-restore-load-balancing-map
      uses: actions/cache/save@v4
      with:
        path: .cypress_load_balancer/main.json
        key: cypress-load-balancer-map-${{ github.base_ref }}-${{ github.head_ref }}-${{ github.run_id }}-${{ github.run_attempt }}

    - name: DEBUG
      run: cat .cypress_load_balancer/main.json
      shell: bash
