name: "cypress-load-balancer/merge"
description: "A simple load balancer for Cypress tests. Merges load balancing maps from parallelized jobs."
author: Zachary J. Hamm
branding:
  icon: "cpu"
  color: "green"

inputs:
  image:
    description: The image to use for running the action
    default: ubuntu-22.04
  node-version:
    description: The node version to use for JS actions
  cache-primary-key:
    description: "Cache primary key for the merged load balancer map"
    default: cypress-load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}

outputs:
  cache-primary-key:
    description: "Cache primary key for the merged load balancer map"
    value: ${{ inputs.cache-primary-key }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - run: |
        yarn install
        yarn build
      shell: bash

    - name: Get cached load-balancing map
      id: cache-restore-load-balancing-map
      uses: actions/cache/restore@v4
      with:
        fail-on-cache-miss: true
        path: .cypress_load_balancer/main.json
        key: cypress-load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          cypress-load-balancer-map-${{github.ref}}

    - name: Download temp maps
      uses: actions/download-artifact@v4
      with:
        pattern: "*-cypress-load-balancer-map-file"
        path: "./cypress_load_balancer_temp"
        merge-multiple: false

    - name: Merge files
      run: npx cypress-load-balancer merge -G "./cypress_load_balancer_temp/**/main.json"
      shell: bash

    - name: Save overwritten cached load-balancing map
      id: cache-save-load-balancing-map
      uses: actions/cache/save@v4
      with:
        path: .cypress_load_balancer/main.json
        #This saves to the workflow run. To save to the trunk, this needs to be uploaded on pull_request merge
        key: ${{ inputs.cache-primary-key }}

    - name: DEBUG
      run: cat .cypress_load_balancer/main.json
      shell: bash
