name: Upload temporary spec map from parallelized Cypress test job

outputs:
  artifact-id:
    description: Artifact ID
    value: ${{ steps.upload-artifact.outputs.artifact-id }}

runs:
  using: "composite"
  steps:
    - name: Upload temp load balancer map
      uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: ${{ github.job }}-cypress-load-balancer-map-temp-from-parallel-job
        path: .cypress_load_balancer/spec-map.json
