# See https://github.com/brennerm/github-actions-pr-close-showcase/
name: Cache load balancing map on base branch
on:
  pull_request:
    types: [closed]

env:
  node-version: 20.18.x

jobs:
  cache_cypress_load_balancing_map:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been merged

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: |
          yarn install
          yarn build

      # Until I can figure out a better way to access cache on head branch, we will need to download it as an artifact
      #      - name: Restore cached load-balancing map on head branch
      #        id: cache-restore-load-balancing-map-head-branch
      #        uses: actions/cache/restore@v4
      #        with:
      #          fail-on-cache-miss: true
      #          path: .cypress_load_balancer/spec-map.json
      #          key: cypress-load-balancer-map-${{ github.head_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
      #          restore-keys: |
      #            cypress-load-balancer-map-${{ github.head_ref }}-

      - name: Download load-balancing map from head branch using "cross-workflow" tooling
        id: download-load-balancing-map-head-branch
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: cypress-parallel.yml
          # Optional, will get head commit SHA
          pr: ${{ github.event.pull_request.number }}
          name: cypress-load-balancer-map
          path: .cypress_load_balancer

      - name: Restore cached load-balancing map on base branch
        id: cache-restore-load-balancing-map-base-branch
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: /temp/.cypress_load_balancer/spec-map.json
          key: cypress-load-balancer-map-${{ github.base_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            cypress-load-balancer-map-${{ github.base_ref }}-

      - name: Merge files
        run: npx cypress-load-balancer merge -G "./temp/.cypress_load_balancer/spec-map.json"

      - name: Save merged load-balancing map
        uses: actions/cache/save@v4
        with:
          path: .cypress_load_balancer/spec-map.json
          key: cypress-load-balancer-map-${{ github.base_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
