name: Cache load balancing map on base branch
on:
  pull_request:
    types:
      - closed
env:
  node-version: 20.18.x

jobs:
  what_is_this:
    - run: echo Merged? ${{github.event.pull_request.merged}}

  cache_cypress_load_balancing_map:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: |
          yarn install
          yarn build

      - name: Restore cached load-balancing map on head branch
        id: cache-restore-load-balancing-map-head-branch
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: .cypress_load_balancer/main.json
          key: cypress-load-balancer-map-${{ github.head_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            cypress-load-balancer-map-${{github.head_ref }}-

      - name: Restore cached load-balancing map on base branch
        id: cache-restore-load-balancing-map-base-branch
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: /temp/.cypress_load_balancer/main.json
          key: cypress-load-balancer-map-${{ github.base_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            cypress-load-balancer-map-${{ github.base_ref }}-

      - name: Merge files
        run: npx cypress-load-balancer merge -G "./temp/.cypress_load_balancer/main.json"

      - name: Save merged load-balancing map
        uses: actions/cache/save@v4
        with:
          path: .cypress_load_balancer/main.json
          key: cypress-load-balancer-map-${{ github.base_ref }}-${{ github.run_id }}-${{ github.run_attempt }}
