name: Cypress testing

on:
  pull_request:
  workflow_dispatch:
    inputs:
      runners:
        type: number
        description: Number of runners to use for parallelization

env:
  runners: ${{ inputs.runners || 3}}
  node-version: 18.20.x

jobs:
  install:
    runs-on: ubuntu-22.04
    outputs:
      specs: ${{ steps.get-specs.outputs.specs }}
      load-balancing-map-cache-primary-key: ${{  steps.cache-load-balancing-map-restore.outputs.cache-primary-key}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: |
          yarn install
          yarn build

      - name: Get cached load-balancing map
        id: cache-load-balancing-map-restore
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: main.json
          #TODO: figure out how to make this exist on the main branch
          key: load-balancing-map

      #      # TODO: figure out how to skip if not existing and use one that exists on the main branch
      #      - name: Download the load balancer file
      #        uses: actions/download-artifact@v4
      #        with:
      #          name: main.json
      #          path: .cypress_load_balancer
      #
      #      #TODO: this is ugly
      #      - run: npx cypress-load-balancer initialize
      #        if: failure()
      #      - name: Create initial map if not existing
      #        if: failure()
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: main.json
      #          path: .cypress_load_balancer/main.json
      #          if-no-files-found: error

      - name: get-specs
        id: get-specs
        run: echo "specs=$(echo $(npx cypress-load-balancer -r ${{ env.runners }} -t e2e --fm string))" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.get-specs.outputs.specs }}

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.install.outputs.specs) }}
    steps:
      - id: generate-uuid
        run: echo uuid="$(uuidgen)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          build: yarn build
          spec: ${{ matrix.spec }}

      - name: Upload temp load balancer map
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.generate-uuid.outputs.uuid }}-parallel-map.json
          path: .cypress_load_balancer/main.json

  merge-maps:
    runs-on: ubuntu-22.04
    needs: [cypress-run, install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: |
          yarn install
          yarn build

      - name: Get cached load-balancing map
        id: cache-load-balancing-map-restore
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: main.json
          #TODO: figure out how to make this exist on the main branch
          key: ${{ needs.install.outputs.load-balancing-map-cache-primary-key }}

      - name: Download temp maps
        uses: actions/download-artifact@v4
        with:
          #          TODO: can't create directories
          #          path: /temp-maps
          pattern: "*-parallel-map.json"
          merge-multiple: true

      - name: Merge files
        run: npx cypress-load-balancer merge -G "*-parallel-map.json"

      #      - name: Upload the merged load balancer file
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: main.json
      #          path: .cypress_load_balancer/main.json
      #
      #
      - name: Save overwritten cached load-balancing map
        id: save-cached-load-balancing-map
        uses: actions/cache/save@v4
        with:
          path: main.json
          #TODO: figure out how to make this exist on the main branch
          key: ${{ needs.install.outputs.load-balancing-map-cache-primary-key }}
