name: Cypress testing

on:
  pull_request:
  workflow_dispatch:
    inputs:
      runners:
        type: number
        description: Number of runners to use for parallelization

env:
  runners: ${{ inputs.runners || 3}}
  node-version: 18.20.x

jobs:
  install:
    runs-on: ubuntu-22.04
    outputs:
      specs: ${{ steps.get-specs.outputs.specs }}
      #TODO: figure out how to make this exist on the main branch
      load-balancing-map-cache-primary-key: load-balancing-map
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: |
          yarn install
          yarn build

      - name: Get cached load-balancing map
        id: cache-restore-load-balancing-map
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: .cypress_load_balancer/main.json
          #TODO: figure out how to make this exist on the main branch
          key: load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            load-balancer-map-${{github.ref}}-
            load-balancer-map-base-${{github.ref}}
            # TODO: trunk branch should have one

            #TODO: this is ugly
      - run: npx cypress-load-balancer initialize
        if: ${{ steps.cache-restore-load-balancing-map.outputs.cache-hit == 'true' }}
      - name: Save initial map if not existing
        if: ${{ steps.cache-restore-load-balancing-map.outputs.cache-hit == 'true' }}
        uses: actions/cache/save@v4
        with:
          path: .cypress_load_balancer/main.json
          #TODO: figure out how to make this exist on the main branch
          key: load-balancer-map-base-${{github.ref}}

      - name: get-specs
        id: get-specs
        run: echo "specs=$(echo $(npx cypress-load-balancer -r ${{ env.runners }} -t e2e --fm string))" >> $GITHUB_OUTPUT

      - name: DEBUG Output load balancing file contents
        run: cat .cypress_load_balancer/main.json

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.install.outputs.specs) }}
    steps:
      - id: generate-uuid
        run: echo uuid="$(uuidgen)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          build: yarn build
          spec: ${{ matrix.spec }}

      - name: Upload temp load balancer map
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.generate-uuid.outputs.uuid }}-parallel-map.json
          path: .cypress_load_balancer/main.json

  merge-maps:
    runs-on: ubuntu-22.04
    needs: [cypress-run, install]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: |
          yarn install
          yarn build

      - name: Get cached load-balancing map
        id: cache-restore-load-balancing-map
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: .cypress_load_balancer/main.json
          #TODO: figure out how to make this exist on the main branch
          key: load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            load-balancer-map-${{github.ref}}-
            load-balancer-map-base-${{github.ref}}

      - name: Download temp maps
        uses: actions/download-artifact@v4
        with:
          pattern: "*-parallel-map.json"
          merge-multiple: true

      - name: Merge files
        run: npx cypress-load-balancer merge -G "*-parallel-map.json"

      - name: DEBUG Output load balancing file contents
        run: cat .cypress_load_balancer/main.json

      - name: Save overwritten cached load-balancing map
        id: cache-save-load-balancing-map
        uses: actions/cache/save@v4
        with:
          path: .cypress_load_balancer/main.json
          #TODO: figure out how to make this exist on the main branch
          #This saves to the workflow run. To save to the trunk, this needs to be uploaded on merge
          key: load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}

