name: Testing load balancing Cypress E2E tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      run_component:
        type: boolean
        description: Get specs for component tests?
        default: true
      run_e2e:
        type: boolean
        description: Get specs for e2e tests?
        default: true
      runners:
        type: number
        description: Number of runners to use for parallelization
      debug:
        type: boolean
        description: Enables debugging on the cypress-load-balancer script

env:
  runners: ${{ inputs.runners || 3}}
  node-version: 18.20.x
  CYPRESS_LOAD_BALANCER_DEBUG: ${{ inputs.debug || false }}
  run_component: ${{inputs.run_component || secrets.CYPRESS_LOAD_BALANCER_RUN_COMPONENT}}
  run_e2e: ${{inputs.run_e2e || secrets.CYPRESS_LOAD_BALANCER_RUN_E2E || true}}

jobs:
  install:
    runs-on: ubuntu-22.04
    outputs:
      e2e-specs: ${{ steps.e2e-cypress-load-balancer.outputs.specs }}
      component-specs: ${{ steps.component-cypress-load-balancer.outputs.specs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: |
          yarn install
          yarn build

      - name: Get cached load-balancing map
        id: cache-restore-load-balancing-map
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: .cypress_load_balancer/main.json
          #TODO: figure out how to make this exist on the main branch
          key: cypress-load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}
          #TODO: trunk branch should have its own restore key
          # Restore keys:
          ## 1. Same key from previous workflow run
          ## 2. Key from pull request base branch
          ## 3. Create new base map if not existing on workflow
          restore-keys: |
            cypress-load-balancer-map-${{github.ref}}-
            cypress-load-balancer-map-${{github.base_ref}}-
            cypress-load-balancer-map-base-${{github.ref}}

      #TODO: this is ugly and incorrect. It should do this if base file does not exist
      - run: npx cypress-load-balancer initialize
        if: ${{ steps.cache-restore-load-balancing-map.outputs.cache-hit == 'true' }}
      - name: Save initial map if not existing
        if: ${{ steps.cache-restore-load-balancing-map.outputs.cache-hit == 'true' }}
        uses: actions/cache/save@v4
        with:
          path: .cypress_load_balancer/main.json
          #TODO: figure out how to make this exist on the main branch
          key: cypress-load-balancer-map-base-${{github.ref}}

      - name: "DEBUG: Output load balancing file contents"
        if: ${{ env.CYPRESS_LOAD_BALANCER_DEBUG != false }}
        run: cat .cypress_load_balancer/main.json

      - name: "E2E: cypress-load-balancer"
        if: ${{ env.run_e2e == true }}
        run: echo "specs=$(echo $(npx cypress-load-balancer -r ${{ env.runners }} -t e2e --fm string))" >> $GITHUB_OUTPUT

      - name: "Component: cypress-load-balancer"
        if: ${{ env.run_component == true }}
        id: component-cypress-load-balancer
        run: echo "specs=$(echo $(npx cypress-load-balancer -r ${{ env.runners }} -t component --fm string))" >> $GITHUB_OUTPUT

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.install.outputs.specs) }}
    steps:
      - id: generate-uuid
        run: echo uuid="$(uuidgen)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          build: yarn build
          spec: ${{ matrix.spec }}
          # Fix for https://github.com/cypress-io/github-action/issues/480
          config: videosFolder=/tmp/cypress-videos

      - name: Upload temp load balancer map
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.generate-uuid.outputs.uuid }}-cypress-load-balancing-maps-from-parallel-jobs
          path: .cypress_load_balancer/main.json

  merge-maps:
    runs-on: ubuntu-22.04
    needs: [cypress-run, install]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Get cached load-balancing map
        id: cache-restore-load-balancing-map
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: .cypress_load_balancer/main.json
          key: cypress-load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            cypress-load-balancer-map-${{github.ref}}-
            cypress-load-balancer-map-base-${{github.ref}}

      - name: Download temp maps
        uses: actions/download-artifact@v4
        with:
          pattern: "*-cypress-load-balancing-maps-from-parallel-jobs"
          path: ./cypress_load_balancer_temp
          merge-multiple: false

      # TEMPORARY FOR THIS JOB
      - run: |
          yarn install
          yarn build

      - name: Merge files
        run: npx cypress-load-balancer merge -G "./cypress_load_balancer_temp/**/main.json"

      - name: "DEBUG: Output load balancing file contents"
        if: ${{ env.CYPRESS_LOAD_BALANCER_DEBUG != false }}
        run: cat .cypress_load_balancer/main.json

      - name: Save overwritten cached load-balancing map
        id: cache-save-load-balancing-map
        uses: actions/cache/save@v4
        with:
          path: .cypress_load_balancer/main.json
          #This saves to the workflow run. To save to the trunk, this needs to be uploaded on merge
          key: cypress-load-balancer-map-${{github.ref}}-${{ github.run_id }}-${{ github.run_attempt }}
