name: Cypress load balancing with custom actions

on:
  pull_request:
  workflow_dispatch:
    inputs:
      run-e2e:
        type: boolean
        description: Get specs for e2e tests?
        default: true
      runners:
        type: number
        description: Number of runners to use for parallelization
        required: false
        default: 3
      debug:
        type: boolean
        description: Enables debugging on the cypress-load-balancer script

env:
  node-version: 18.20.x
  runners: ${{ inputs.runners || secrets.CYPRESS_LOAD_BALANCER_RUNNERS  || 3}}
  CYPRESS_LOAD_BALANCER_DEBUG: ${{ inputs.debug || false }}
  CYPRESS_LOAD_BALANCING_MAX_DURATIONS_ALLOWED: ${{ secrets.CYPRESS_LOAD_BALANCING_MAX_DURATIONS_ALLOWED }}

jobs:
  get_specs_e2e:
    runs-on: ubuntu-22.04
    outputs:
      specs: ${{ steps.cypress-load-balancer-get-specs-e2e.outputs.specs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - uses: actions/setup-node@v4
#        with:
#          node-version: ${{ env.node-version }}

      - uses: ./actions/get_specs
        id: cypress-load-balancer-get-specs-e2e
        with:
          testing-type: e2e
          node-version: ${{ env.node-version }}

  cypress_run_e2e:
    runs-on: ubuntu-22.04
    needs: get_specs_e2e
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.get_specs_e2e.outputs.specs) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          build: yarn build
          spec: ${{ matrix.spec }}
          # Fix for https://github.com/cypress-io/github-action/issues/480
          config: videosFolder=/tmp/cypress-videos

      - uses: ./actions/cache
        with:
          node-version: ${{ env.node-version }}

  merge_cypress_load_balancing_maps:
    runs-on: ubuntu-22.04
    needs: [get_specs_e2e, cypress_run_e2e]
    if: ${{ needs.get_specs_e2e.result == 'success' }}
    steps:
      - uses: ./actions/merge
        with:
          node-version: ${{ env.node-version }}
