name: TypeScript checking and linting
on:
  pull_request:

env:
  node-version: 18.20.x

jobs:
  tsc:
    name: TypeScript Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - run: |
          yarn install
          yarn run dev:check
          yarn run dev:check:tests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - run: |
          yarn install
          yarn run dev:lint
